[metadata]
name = pyannote-audio
description = Neural speaker diarization
author = Herve Bredin
author_email = herve.bredin@irit.fr
license = mit
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8; variant=GFM
platforms = Linux, Mac
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python

[options]
zip_safe = False
packages = find:
include_package_data = True
# УДАЛЕНА строка: setup_requires = pyscaffold>=3.2a0,<3.3a0
python_requires = >=3.9

[options.packages.find]
where = .
exclude =
    tests

[options.extras_require]
testing =
    pytest>=6.0
    pytest-cov>=2.10
    jupyter
    papermill
dev =
    pre_commit>=2.7
    recommonmark>=0.6
    black>=22.3.0
cli =
    hydra-core >=1.1,<1.2
    typer >= 0.4.0,<0.5.0
separation =
    transformers >= 4.39.1
    asteroid >=0.7.0

[options.entry_points]
console_scripts =
    pyannote-audio-train=pyannote.audio.cli.train:train
    pyannote-audio-eval=pyannote.audio.cli.evaluate:evaluate

[test]
extras = True

[tool:pytest]
addopts =
    --cov pyannote --cov-report term-missing
    --verbose
norecursedirs =
    dist
    build
    .tox
testpaths = tests

[aliases]
dists = bdist_wheel

[bdist_wheel]

[build_sphinx]
source_dir = doc
build_dir = build/sphinx

[devpi:upload]
no-vcs = 1
formats = bdist_wheel

[flake8]
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py